version: '3.0'

services:
  dbpostgress:
    image: postgres:latest
    container_name: dbpostgress

    # - Agregar network_mode: bridge, evitará que cree una red.
    # - Problema: Soluciona problema que no se ve la bd entre contenedores
    # - Para las apps que necesiten la ip de dbpostgress se puede 
    # utilizar la 'ip del contenedor' o la 'ip de la network bridge'
    # => docker network inspect bridge 
    # => "IPAM": {"Config": [{"Gateway": "<IP_BRIDGE>"}]}
    # => "Containers": {"<ID_CONTAINER>": {"IPv4Address": "<IP_CONTINER>"}
    network_mode: bridge 
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - 8081:8080
      - 5432:5432
      - 3309:3306
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
