version: '3.0'

services:
  db-postgress:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - 8080:8080
      - 5432:5432
