# version: 1.0
version: '3'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    restart: unless-stopped
    deploy:
      resources:
          limits:
            cpus: '4'
            memory: 8000M
          # reservations:
          #   cpus: 2
          #   memory: 4000M
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1901:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Chile/Continental
      - PLEX_CLAIM=claim-zb3Tq4g6wn9rhdZQzJPz
      - ADVERTISE_IP=http://localhost:32400/
    hostname: MAQUINA1
    volumes:
    # Path plex
      - ./plex/config:/config
    # Path plex - others
      - ./plex/transcode:/transcode
    # Path videos
      - ./Multimedia:/Multimedia

# ======================================================================================================
