version: '3'

services:
  db-mongo:
    image: mongo:latest
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
    ports:
      - 27017:27017
