stages:
  - build

# build-and-push: contruye la imagen y la sube al registry privado
build-and-push:
  stage: build
  image: docker:19.03.12
  services:
    # usara servicio docker in docker
    - docker:19.03.12-dind
  variables:  # variables locales
    FULL_NAME_PROJECT: img-$CI_PROJECT_NAME
  script:
    - docker build -t $FULL_NAME_PROJECT .
    - docker tag $FULL_NAME_PROJECT $MY_REGISTRY_URL/$FULL_NAME_PROJECT:1.0.0
    - docker push $MY_REGISTRY_URL/$FULL_NAME_PROJECT:1.0.0
  rules: 
    #Solo se ejecuta en master 
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      # Indica siempre
      when: always
  tags: 
     # hace referencia al tag runner 
    - runner-docker